### PR TITLE
dbg: testing a larger BW to grab extra signals/spots

### PR DESCRIPTION
**Pull request by Guenael**
cc @dforsi @mkarliner
you might be interested in testing this branch.

### CODE REVIEW

**Comment by Guenael** [comment]
I will NOT merge this branch right now.

**Comment by mkarliner** [comment]
Being trying this morning on 40. 
It's not providing dramatically more spots, but it's not 
that easy to tell if there is or isn't an improvement.
At this time of year, the bands go up a down a lot over quite short
periods of time.
If I get the chance, I'll try piping wsprd | wc with each branch.

**Comment by mkarliner** [comment]
BTW, another column in the output for offset would help in identifying wide bandwidth signals.

**Comment by dforsi** [comment]
Thank you Guenal, however I don't think that I can make meaningful tests because I only have one antenna for HF and no external tuner, I use it with the internal tuner of my transceiver and one antenna for VHF/UHF, but there aren't WSPR transmitters on VHF/UHF near enough anyway.

I'll let this branch of rtlsdr-wsprd run overnight with this command line
`./rtlsdr_wsprd -f 80m -u 125M -c IU5HKX -l JN53fj -w 80m_fir`
, but for now I'm only getting wrong decodes
```
              Date  Time(z)    SNR     DT       Freq Dr    Call    Loc Pwr
Allocating 15 zero-copy buffers
Spot :  2021-12-20 23:20:00 -22.29  -4.73   3.594102  0   <...> A000AA 63
No spot 2021-12-20 23:22z
No spot 2021-12-20 23:24z
No spot 2021-12-20 23:26z
No spot 2021-12-20 23:28z
Spot :  2021-12-20 23:30:00 -24.14  -0.91   3.594202  0   <...> A000AA 63
No spot 2021-12-20 23:32z
No spot 2021-12-20 23:34z
No spot 2021-12-20 23:36z
Spot :  2021-12-20 23:38:00 -22.79  -1.74   3.594102  0   <...> A000AA 63
Spot :  2021-12-20 23:38:00 -25.20  -3.19   3.594202  0   <...> A000AA 63
No spot 2021-12-20 23:40z
Spot :  2021-12-20 23:42:00 -22.22   3.80   3.594102  0   <...> A000AA 63
```
These are the .iq file for some of the spots above:
* [80m_fir_2021-12-20_23-20-00.zip](https://github.com/Guenael/rtlsdr-wsprd/files/7748489/80m_fir_2021-12-20_23-20-00.zip)
* [80m_fir_2021-12-20_23-30-00.zip](https://github.com/Guenael/rtlsdr-wsprd/files/7748493/80m_fir_2021-12-20_23-30-00.zip)
* [80m_fir_2021-12-20_23-38-00.zip](https://github.com/Guenael/rtlsdr-wsprd/files/7748517/80m_fir_2021-12-20_23-38-00.zip)

**Comment by Guenael** [comment]
Yep, there is nothing visible on these sample. BTW, what kind of up-converter did you used?
I will update to the latest version of wsprd, and hope for a fix with these wrong spots, otherwise, I will add a str cmp test to remove them.

**Comment by dforsi** [comment]
My upconverter is a no-brand based on the NE602 mixer.

**Comment by Guenael** [comment]
@dforsi I will finish this branch https://github.com/Guenael/rtlsdr-wsprd/tree/lib-update , and we will see if a recent version of wsprd fix this issue. Otherwise, I will drop this callsign.

**Comment by Guenael** [comment]
Additional BW not required here (cf. decoding bw limited +/-150Hz by another FIR).

**Pull request closed without merging**
